//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_wycieczki_koncowy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Images
    {
        public int Id { get; set; }
        [Display(Name = "Zdjêcia z wycieczki")]
        public string ImgData { get; set; }
        public Nullable<int> WycieczkaID { get; set; }
    
        public virtual Wycieczki Wycieczki { get; set; }
    }
}
