//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_wycieczki_koncowy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Wycieczki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wycieczki()
        {
            this.Images = new HashSet<Images>();
        }
    
        public int Id { get; set; }

        [Display(Name = "Miejsce pocz¹tkowe")]
        [Required(ErrorMessage = "Miejscowoœæ pocz¹tkowa jest wymagana.")]
        [StringLength(49, ErrorMessage = "Zbyt d³uga nazwa miejscowoœci")]
        public string Msc_start { get; set; }

        [Display(Name = "Miejsce koñcowe")]
        [Required(ErrorMessage = "Miejscowoœæ koñcowa jest wymagana.")]
        [StringLength(49, ErrorMessage = "Zbyt d³uga nazwa miejscowoœci")]
        public string Msc_end { get; set; }



        [Display(Name = "Data wycieczki")]
        [Required(ErrorMessage = "Data jest wymagana.")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [CurrentDate(ErrorMessage ="Data musi byæ z przesz³oœci")]
        public DateTime? Data { get; set; }

        [Display(Name = "Liczba przebytych kilometrów")]
        [Required(ErrorMessage = "Liczba kilometrów jest wymagana.")]
        [StringLength(49, ErrorMessage = "Zbyt d³uga iloœæ znaków")]
        public string Liczba_km { get; set; }

        [Display(Name = "Czas trwania wyciczki(dni)")]
        [Required(ErrorMessage = "Liczba dni jest wymagana.")]
        [StringLength(49, ErrorMessage = "Zbyt d³uga iloœæ znaków")]
        public string Liczba_dni { get; set; }

        [Display(Name = "Plik wideo")]
        public string VideoFile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Display(Name = "Zdjêcia z wycieczki")]
        public virtual ICollection<Images> Images { get; set; }
        [Display(Name = "Zdjêcia z wycieczki")]
        public virtual Images images_needed { get; set; }
    }
}
